extends Node
## EventDB — all static content. Original world ("The Reach"). No protected IP.
## Pure data: safe to expand toward the 80-150 event / 4-6 route production target.

# --- 8 resources (money is one of them) ---
const RESOURCES := ["food", "water", "medicine", "ammo", "parts", "clothing", "feed", "money"]

const RESOURCE_LABELS := {
	"food": "Food", "water": "Water", "medicine": "Medicine", "ammo": "Ammo",
	"parts": "Parts", "clothing": "Clothing", "feed": "Feed", "money": "Coin",
}

const OUTFITTER_PRICES := {
	"food": 1, "water": 1, "medicine": 6, "ammo": 2,
	"parts": 8, "clothing": 4, "feed": 1,
}

const DAILY_CONSUMPTION := {
	"food": 2, "water": 2, "feed": 1,
}

# --- 5 selectable leaders ---
const LEADERS := [
	{"name": "Captain Mara Voss", "trait": "Steady",   "bonus": "morale_decay_slow",
		"blurb": "A former caravan guard. Her calm keeps the party together longer."},
	{"name": "Doc Elias Renn",    "trait": "Healer",   "bonus": "medicine_efficient",
		"blurb": "A field surgeon. Medicine goes twice as far in his hands."},
	{"name": "Tess Bowery",       "trait": "Scout",    "bonus": "event_luck",
		"blurb": "Knows the wild. Risky choices fail less often."},
	{"name": "Old Hale",          "trait": "Tinker",   "bonus": "parts_efficient",
		"blurb": "A wagon-wright. Repairs cost fewer parts."},
	{"name": "Junia Cole",        "trait": "Trader",   "bonus": "cheap_outfit",
		"blurb": "A sharp haggler. Supplies cost 20% less at the outfitter."},
]

const PARTY_TEMPLATE := [
	{"name": "Sam",  "trait": "Tough"},
	{"name": "Rhea", "trait": "Cook"},
	{"name": "Boone","trait": "Hunter"},
	{"name": "Lila", "trait": "Quiet"},
]

# --- Wagon types (3) — tradeoffs, no pay-to-win ---
const WAGONS := [
	{"id":"scout",    "name":"Scout Cart",    "miles_mult":1.25, "parts_resist":0.0, "start_money":0,
		"blurb":"Light and fast (+25% miles) but fragile. For aggressive runs."},
	{"id":"settler",  "name":"Settler Wagon", "miles_mult":1.0,  "parts_resist":0.25, "start_money":10,
		"blurb":"Balanced and sturdy. The reliable default."},
	{"id":"freighter","name":"Freighter",     "miles_mult":0.8,  "parts_resist":0.5,  "start_money":20,
		"blurb":"Slow (-20% miles) but tough and roomy (+20 starting coin)."},
]

# --- Cosmetic skins (Month-6 monetization; purely visual, never affects play) ---
const SKINS := [
	{"id":"default", "name":"Trailworn",   "tint":"e0a458"},
	{"id":"crimson", "name":"Crimson Road", "tint":"eb5757"},
	{"id":"emerald", "name":"Greenway",     "tint":"6fcf97"},
	{"id":"ironclad","name":"Ironclad",     "tint":"9aa7bd"},
]

# --- Routes (3 of the 4-6 production target). biome drives weather table. ---
const ROUTES := [
	{"id":"ashford",  "name":"The Ashford Reach", "total_miles":800,  "biome":"temperate", "difficulty":"Medium",
		"intro":"Eight hundred miles of broken country lie between Fort Kestrel and the green valleys of Ashford. Load the wagon. Choose your road. Not everyone arrives."},
	{"id":"saltpan",  "name":"The Saltpan Crossing", "total_miles":600, "biome":"desert", "difficulty":"Hard",
		"intro":"Six hundred miles of salt flats and dead air. Water is everything here. Leave Greywell with full casks or don't leave at all."},
	{"id":"wintergale","name":"Wintergale Pass", "total_miles":1000, "biome":"alpine", "difficulty":"Brutal",
		"intro":"A thousand miles over the spine of the world. The cold does not negotiate. Clothing and feed matter as much as courage."},
	{"id":"mire", "name":"The Drowned Mire", "total_miles":700, "biome":"swamp", "difficulty":"Hard",
		"intro":"Seven hundred miles of black water and rotting timber. The mire breeds sickness and swallows wagons whole. Keep your medicine close."},
	{"id":"coast","name":"The Shattered Coast", "total_miles":900, "biome":"coast", "difficulty":"Hard",
		"intro":"Nine hundred miles along a storm-battered shore. The sea gives fish and takes wagons. Watch the tide and the sky."},
]

# Weather tables per biome: id, label, consume_mult, event_bonus, morale, miles_mult
const WEATHER := {
	"clear": {"label":"Clear", "consume_mult":1.0, "event_bonus":0.0, "morale":1, "miles_mult":1.0},
	"rain":  {"label":"Rain",  "consume_mult":1.0, "event_bonus":0.05,"morale":-1,"miles_mult":0.9},
	"storm": {"label":"Storm", "consume_mult":1.1, "event_bonus":0.15,"morale":-3,"miles_mult":0.75},
	"heat":  {"label":"Heat",  "consume_mult":1.3, "event_bonus":0.1, "morale":-2,"miles_mult":0.9},
	"snow":  {"label":"Snow",  "consume_mult":1.2, "event_bonus":0.1, "morale":-2,"miles_mult":0.7},
	"fog":   {"label":"Fog",   "consume_mult":1.0, "event_bonus":0.1, "morale":-1,"miles_mult":0.85},
}

const BIOME_WEATHER := {
	"temperate": ["clear","clear","clear","rain","rain","storm","fog"],
	"desert":    ["clear","clear","heat","heat","heat","storm","clear"],
	"alpine":    ["clear","snow","snow","snow","storm","fog","clear"],
	"swamp":     ["clear","rain","rain","fog","fog","storm","rain"],
	"coast":     ["clear","clear","rain","fog","storm","clear","rain"],
}

# --- 20 recruitable characters (joined via events) ---
const RECRUITS := [
	{"name":"Cass",   "trait":"Tracker",  "blurb":"A quiet woman who reads the land like a book."},
	{"name":"Eli",    "trait":"Preacher", "blurb":"Carries a worn bible and an easy calm."},
	{"name":"Nan",    "trait":"Midwife",  "blurb":"Healer's hands and a healer's patience."},
	{"name":"Roy",    "trait":"Smith",    "blurb":"Broad-shouldered, good with a hammer and a wheel."},
	{"name":"Pip",    "trait":"Orphan",   "blurb":"Half-grown, all heart, eats little."},
	{"name":"Dell",   "trait":"Veteran",  "blurb":"An old soldier who's seen worse than this."},
	{"name":"Mabel",  "trait":"Cook",     "blurb":"Can stretch a thin larder a long way."},
	{"name":"Cort",   "trait":"Gambler",  "blurb":"Lucky, loud, and quick with a deck."},
	{"name":"Yara",   "trait":"Trapper",  "blurb":"Knows where the game runs."},
	{"name":"Finn",   "trait":"Boatman",  "blurb":"Grew up on rivers; fears no crossing."},
	{"name":"Greta",  "trait":"Herbalist","blurb":"Finds medicine where others see weeds."},
	{"name":"Asa",    "trait":"Drover",   "blurb":"The oxen trust him more than they trust you."},
	{"name":"Lupe",   "trait":"Scout",    "blurb":"Fast, fearless, first to spot trouble."},
	{"name":"Ott",    "trait":"Tinker",   "blurb":"A pocket full of odd parts and ideas."},
	{"name":"Briar",  "trait":"Hunter",   "blurb":"Steady aim, steadier nerves."},
	{"name":"Sela",   "trait":"Trader",   "blurb":"Never met a deal she couldn't sweeten."},
	{"name":"Marsh",  "trait":"Guide",    "blurb":"Has walked these roads before, mostly."},
	{"name":"June",   "trait":"Nurse",    "blurb":"Soft voice, iron stomach."},
	{"name":"Hollis", "trait":"Carpenter","blurb":"Can rebuild a wagon from a woodpile."},
	{"name":"Wren",   "trait":"Singer",   "blurb":"Keeps the dark at bay with a tune."},
]

# --- Named illness conditions (original; no branded gags) ---
# A member can carry conditions; each drains health/day until cured by medicine or rest.
const ILLNESSES := {
	"fever":      {"name":"Trail Fever",   "drain":4, "cure_med":2},
	"campsick":   {"name":"Camp Sickness", "drain":5, "cure_med":2},
	"exhaustion": {"name":"Exhaustion",    "drain":3, "cure_med":0},  # cured by Rest
	"frostbite":  {"name":"Frostbite",     "drain":4, "cure_med":3},
	"heatstroke": {"name":"Heatstroke",    "drain":5, "cure_med":1},
	"injury":     {"name":"Broken Limb",   "drain":3, "cure_med":3},
}

# --- Events (38). choice schema unchanged + optional "minigame":"hunt" / "relationship". ---
const EVENTS := [
	{"id":"river_ford","title":"The Cold River","weight":3,
		"text":"A wide river blocks the trail. The ford looks shallow but the current is fast.",
		"choices":[
			{"text":"Ford it now (risky, free)","chance":0.6,
				"on_success":{"log":"You cross clean. Wheels hold."},
				"on_fail":{"res":{"parts":-2,"food":-8},"health":{"amount":-15,"target":"random"},
					"inflict":{"who":"random","cond":"injury"},
					"log":"The wagon lurches. Gear washes downstream and someone is hurt."}},
			{"text":"Pay the ferryman (6 coin)","effects":{"res":{"money":-6},"log":"Slow, dull, safe. You cross dry."}},
			{"text":"Wait two days for low water","effects":{"res":{"food":-4,"water":-4,"feed":-2},"morale":-3,
				"log":"The water drops. The waiting frays nerves."}},
		]},
	{"id":"fever","title":"Trail Fever","weight":3,
		"text":"One of the party wakes shivering and slick with sweat.",
		"choices":[
			{"text":"Dose with medicine","effects":{"res":{"medicine":-2},"cure":{"who":"worst","cond":"fever"},
				"health":{"amount":8,"target":"worst"},"log":"The fever breaks by morning."}},
			{"text":"Rest a day, no medicine","effects":{"res":{"food":-4,"water":-4},"morale":-2,
				"inflict":{"who":"worst","cond":"fever"},"log":"You lose a day. They mend, slowly."}},
			{"text":"Push on regardless","effects":{"inflict":{"who":"random","cond":"fever"},"morale":-4,
				"log":"You make miles, but the sickness deepens."}},
		]},
	{"id":"hunt","title":"Game on the Ridge","weight":3,
		"text":"A herd grazes on the next ridge. Steady your aim — fresh meat is on the line.",
		"choices":[
			{"text":"Hunt (mini-game, uses ammo)","minigame":"hunt","effects":{"res":{"ammo":-3}}},
			{"text":"Leave them be","effects":{"log":"You keep moving. The wagon stays quiet."}},
		]},
	{"id":"broken_axle","title":"Cracked Axle","weight":2,
		"text":"A wheel drops into a rut. The front axle splinters.",
		"choices":[
			{"text":"Repair with parts","effects":{"res":{"parts":-3},"log":"An afternoon's work and you roll again."}},
			{"text":"Lash it and limp on","effects":{"res":{"feed":-3},"morale":-3,"health":{"amount":-5,"target":"random"},
				"log":"The wagon groans for miles. Hard riding on everyone."}},
		]},
	{"id":"stranger","title":"A Stranger on the Road","weight":2,
		"text":"A lone traveler hails you, asking to join the party for safety.",
		"choices":[
			{"text":"Welcome them","effects":{"morale":6,"res":{"food":-6,"water":-6},
				"log":"Good company. Also one more belly to feed."}},
			{"text":"Send them off","effects":{"morale":-4,"log":"You move on. The choice sits heavy."}},
			{"text":"Trade news only","effects":{"morale":2,"res":{"money":2},
				"log":"They mark a shortcut on your map and tip you a coin for bread."}},
		]},
	{"id":"storm","title":"Black Sky","weight":3,
		"text":"A wall of storm rolls in fast across open ground.",
		"choices":[
			{"text":"Make camp and ride it out","effects":{"res":{"food":-3,"feed":-2},"log":"Soaked but safe."}},
			{"text":"Drive through it","chance":0.5,
				"on_success":{"log":"You outrun the worst of it and gain ground."},
				"on_fail":{"res":{"clothing":-3,"parts":-1},"health":{"amount":-10,"target":"all"},"morale":-3,
					"log":"Lightning, hail, panic. Everyone suffers."}},
		]},
	{"id":"contaminated_water","title":"Bad Water","weight":2,
		"text":"The only spring for miles smells of rot.",
		"choices":[
			{"text":"Boil it (costs a day)","effects":{"res":{"food":-3,"water":15},"morale":-1,
				"log":"Slow, but the casks are full and clean."}},
			{"text":"Drink it anyway","chance":0.4,
				"on_success":{"res":{"water":15},"log":"It was fine. You got lucky."},
				"on_fail":{"res":{"water":15},"inflict":{"who":"all","cond":"campsick"},
					"log":"By night the whole party is doubled over."}},
			{"text":"Press on dry","effects":{"res":{"water":-6},"morale":-3,"log":"Thirsty miles."}},
		]},
	{"id":"wagon_trader","title":"Wayside Trader","weight":2,
		"text":"A trading post sits at a crossroads, wares spread on a blanket.",
		"choices":[
			{"text":"Buy medicine (8 coin)","effects":{"res":{"money":-8,"medicine":3},"log":"A fair deal for hard times."}},
			{"text":"Sell spare parts (+10 coin)","effects":{"res":{"money":10,"parts":-3},"log":"Coin in hand, lighter load."}},
			{"text":"Just water the animals","effects":{"res":{"feed":4},"log":"The oxen drink their fill."}},
		]},
	{"id":"theft","title":"Night Raiders","weight":2,
		"text":"You wake to figures slipping among the supplies.",
		"choices":[
			{"text":"Fire a warning shot","chance":0.7,
				"on_success":{"res":{"ammo":-1},"log":"They scatter into the dark. Nothing lost."},
				"on_fail":{"res":{"ammo":-1,"food":-12,"money":-5},"log":"A scuffle. They get away with food and coin."}},
			{"text":"Stay hidden, let them take a little","effects":{"res":{"food":-8},"morale":-2,
				"log":"You keep your skin. They keep your bread."}},
		]},
	{"id":"lost_trail","title":"The Trail Forks","weight":2,
		"text":"The path splits and your map disagrees with the ground.",
		"choices":[
			{"text":"Take the canyon (faster, risky)","chance":0.6,
				"on_success":{"res":{"food":-2},"log":"A shortcut. You save half a day."},
				"on_fail":{"res":{"food":-8,"feed":-4},"morale":-3,"log":"A dead end. Backtracking costs you dearly."}},
			{"text":"Stay on the ridge road (safe)","effects":{"res":{"food":-4,"feed":-2},"log":"Longer, but sure."}},
		]},
	{"id":"snakebite","title":"Snakebite","weight":2,
		"text":"A rattler strikes from the brush.",
		"choices":[
			{"text":"Treat with medicine","effects":{"res":{"medicine":-2},"health":{"amount":4,"target":"worst"},
				"log":"You draw the venom in time."}},
			{"text":"Cut and pray","chance":0.45,
				"on_success":{"health":{"amount":-4,"target":"worst"},"log":"They pull through, shaken."},
				"on_fail":{"health":{"amount":-22,"target":"worst"},"morale":-5,"inflict":{"who":"worst","cond":"injury"},
					"log":"A bad night. The leg swells black."}},
		]},
	{"id":"morale_song","title":"A Fire and a Song","weight":2,
		"text":"The party is worn thin. Someone pulls out a fiddle.",
		"choices":[
			{"text":"Rest and sing (costs food)","effects":{"res":{"food":-4},"morale":10,"bond":{"who":"all","amount":6},
				"log":"Laughter for the first time in days."}},
			{"text":"No time — keep watch","effects":{"morale":-2,"log":"The fiddle stays in its case."}},
		]},
	{"id":"abandoned_wagon","title":"Abandoned Wagon","weight":2,
		"text":"A wrecked wagon sits half-buried in dust, its owners long gone.",
		"choices":[
			{"text":"Salvage it","effects":{"res":{"parts":2,"clothing":2,"food":4},"morale":-2,
				"log":"Useful gear. A grim reminder of the road."}},
			{"text":"Leave it untouched","effects":{"morale":2,"log":"You let the dead keep their things."}},
		]},
	{"id":"heat","title":"Dead Heat","weight":2,
		"text":"The sun hammers a treeless flat. The animals stagger.",
		"choices":[
			{"text":"Travel by night","effects":{"res":{"water":-4},"morale":-1,"log":"Cooler going, but no real rest."}},
			{"text":"Push through the day","effects":{"res":{"water":-10,"feed":-4},"inflict":{"who":"random","cond":"heatstroke"},
				"log":"Heat fells one of the party."}},
		]},
	{"id":"sick_ox","title":"Ailing Ox","weight":2,
		"text":"One of the draft animals goes lame.",
		"choices":[
			{"text":"Rest and feed it","effects":{"res":{"feed":-5,"food":-3},"log":"It recovers. You lose a little ground."}},
			{"text":"Press on, half team","effects":{"res":{"parts":-1},"morale":-2,"health":{"amount":-4,"target":"random"},
				"log":"Slow, jolting miles on a tired wagon."}},
		]},
	{"id":"gift","title":"Kindness of Strangers","weight":1,
		"text":"A settler family shares their table as you pass.",
		"choices":[
			{"text":"Accept gratefully","effects":{"res":{"food":12,"water":8},"morale":6,
				"log":"A warm meal and full casks. The world feels less cruel."}},
			{"text":"Pay them for it (4 coin)","effects":{"res":{"money":-4,"food":12,"water":8},"morale":3,
				"log":"You insist on paying. They wave you off with extra bread."}},
		]},
	{"id":"quarrel","title":"A Quarrel","weight":2,
		"text":"Two of the party come to blows over the last of the rations.",
		"choices":[
			{"text":"Side with one","effects":{"morale":-6,"bond":{"who":"random","amount":-10},"log":"The wagon splits into camps."}},
			{"text":"Ration fairly and mediate","effects":{"res":{"food":-3},"morale":4,"bond":{"who":"all","amount":3},
				"log":"You divide it even. Tempers cool."}},
		]},
	{"id":"cliff_road","title":"The Cliff Road","weight":2,
		"text":"The trail narrows to a ledge above a long drop.",
		"choices":[
			{"text":"Lead the team on foot","chance":0.75,
				"on_success":{"res":{"food":-2},"log":"Inch by inch, you make it across."},
				"on_fail":{"res":{"parts":-3,"clothing":-2},"health":{"amount":-18,"target":"random"},
					"inflict":{"who":"random","cond":"injury"},
					"log":"A wheel slips. You save the wagon but not unscathed."}},
			{"text":"Detour the long way","effects":{"res":{"food":-8,"water":-6,"feed":-4},"morale":-2,
				"log":"Safe, but it costs you days."}},
		]},
	{"id":"wolves","title":"Wolves at the Edge","weight":2,
		"text":"Eyes glint at the treeline. The pack is hungry.",
		"choices":[
			{"text":"Drive them off (ammo)","effects":{"res":{"ammo":-2},"log":"A few shots and they melt away."}},
			{"text":"Build up the fire (food)","effects":{"res":{"food":-4},"morale":-1,
				"log":"You burn through stores to keep the dark back."}},
		]},
	{"id":"clear_run","title":"Open Country","weight":3,
		"text":"For once the land is kind: flat, green, and quiet.",
		"choices":[
			{"text":"Make good miles","effects":{"morale":3,"log":"An easy day. Spirits lift."}},
			{"text":"Rest the animals and forage","effects":{"res":{"food":8,"feed":4},"morale":2,
				"log":"You gather wild greens and let the team graze."}},
		]},
	# --- expansion set ---
	{"id":"scavenge","title":"Scavenge the Hollow","weight":2,
		"text":"A wooded hollow might hide forage and game.",
		"choices":[
			{"text":"Forage carefully (mini-game)","minigame":"hunt","effects":{"res":{"ammo":-1}}},
			{"text":"Skip it","effects":{"log":"Not worth the daylight."}},
		]},
	{"id":"frost_night","title":"A Killing Frost","weight":2,
		"text":"The temperature plunges after dark.",
		"choices":[
			{"text":"Break out extra clothing","effects":{"res":{"clothing":-3},"log":"Bundled tight, you weather it."}},
			{"text":"Huddle and ration heat","effects":{"inflict":{"who":"random","cond":"frostbite"},"morale":-2,
				"log":"By dawn someone can't feel their fingers."}},
		]},
	{"id":"trade_post","title":"Greywell Post","weight":2,
		"text":"A proper trading post — a chance to rebalance the wagon.",
		"choices":[
			{"text":"Buy food x10 (8 coin)","effects":{"res":{"money":-8,"food":10},"log":"Stocked the larder."}},
			{"text":"Buy feed x10 (8 coin)","effects":{"res":{"money":-8,"feed":10},"log":"The animals will thank you."}},
			{"text":"Sell clothing for coin","effects":{"res":{"money":8,"clothing":-3},"log":"Lighter, richer, colder."}},
		]},
	{"id":"deserter","title":"One Wants to Turn Back","weight":2,
		"text":"A member loses heart and talks of going home.",
		"choices":[
			{"text":"Talk them down","chance":0.7,
				"on_success":{"morale":4,"bond":{"who":"random","amount":8},"log":"They stay. The bond holds."},
				"on_fail":{"morale":-6,"bond":{"who":"random","amount":-8},"log":"Words fail. The mood sours."}},
			{"text":"Let them stew","effects":{"morale":-3,"log":"You say nothing. The silence stretches."}},
		]},
	{"id":"mud","title":"Mired Wheels","weight":2,
		"text":"Spring melt turns the trail to a sea of mud.",
		"choices":[
			{"text":"Dig and push (hard labor)","effects":{"res":{"food":-3},"health":{"amount":-4,"target":"all"},
				"log":"Filthy, exhausting work — but you're free."}},
			{"text":"Wait for it to dry","effects":{"res":{"food":-5,"water":-3,"feed":-3},"morale":-2,
				"log":"Days lost to the mud."}},
		]},
	{"id":"berries","title":"Wild Berries","weight":1,
		"text":"A thicket heavy with unfamiliar berries.",
		"choices":[
			{"text":"Eat your fill","chance":0.6,
				"on_success":{"res":{"food":8},"morale":2,"log":"Sweet and safe. A small mercy."},
				"on_fail":{"inflict":{"who":"all","cond":"campsick"},"log":"They turn out to be the wrong kind."}},
			{"text":"Leave them","effects":{"log":"Better hungry than poisoned."}},
		]},
	{"id":"avalanche","title":"Loaded Slope","weight":2,
		"text":"Fresh snow hangs heavy above the pass.",
		"choices":[
			{"text":"Cross fast and quiet","chance":0.6,
				"on_success":{"log":"You slip across before the slope lets go."},
				"on_fail":{"res":{"parts":-3,"feed":-4},"health":{"amount":-16,"target":"random"},
					"inflict":{"who":"random","cond":"injury"},"log":"A slide catches the wagon's tail."}},
			{"text":"Wait for it to settle","effects":{"res":{"food":-6,"feed":-4,"clothing":-2},"morale":-2,
				"log":"A cold, anxious wait."}},
		]},
	{"id":"old_friend","title":"A Familiar Face","weight":1,
		"text":"Someone from the leader's past crosses the trail.",
		"choices":[
			{"text":"Share a fire and stories","effects":{"morale":6,"bond":{"who":"all","amount":5},"res":{"food":-3},
				"log":"Old ties, rekindled. The party feels lighter."}},
			{"text":"Keep it brief","effects":{"morale":1,"log":"A nod, a word, and onward."}},
		]},
	{"id":"dry_well","title":"The Dry Well","weight":2,
		"text":"The mapped waterhole is cracked mud.",
		"choices":[
			{"text":"Dig for seep water","chance":0.5,
				"on_success":{"res":{"water":10},"morale":-1,"log":"You find muddy water — enough."},
				"on_fail":{"res":{"water":-4},"morale":-3,"log":"Nothing but dust and blistered hands."}},
			{"text":"Push to the next source","effects":{"res":{"water":-8,"feed":-3},"log":"A long dry stretch."}},
		]},
	{"id":"toll","title":"The Tollkeeper","weight":1,
		"text":"An armed party controls the only bridge.",
		"choices":[
			{"text":"Pay the toll (8 coin)","effects":{"res":{"money":-8},"log":"Highway robbery, but you cross."}},
			{"text":"Refuse and detour","effects":{"res":{"food":-6,"feed":-4,"water":-4},"morale":-2,
				"log":"The long way around, on principle."}},
			{"text":"Intimidate them","chance":0.4,
				"on_success":{"log":"You stare them down. They wave you through."},
				"on_fail":{"res":{"money":-10,"food":-6},"morale":-3,"log":"It goes badly. They take more than coin."}},
		]},
	{"id":"medicine_cache","title":"A Doctor's Cache","weight":1,
		"text":"An old field-kit, abandoned but intact.",
		"choices":[
			{"text":"Take it","effects":{"res":{"medicine":4},"morale":2,"log":"A windfall of medicine."}},
		]},
	{"id":"exhausted","title":"Worn to the Bone","weight":2,
		"text":"The pace has caught up with the party. Heads droop.",
		"choices":[
			{"text":"Force a full rest day","effects":{"res":{"food":-4,"water":-4},"morale":6,
				"cure":{"who":"all","cond":"exhaustion"},"log":"A day's rest. The party comes back to life."}},
			{"text":"One more hard push","effects":{"inflict":{"who":"random","cond":"exhaustion"},"morale":-3,
				"log":"You squeeze out more miles, but at a cost."}},
		]},
	{"id":"river_swell","title":"A Risen River","weight":2,
		"text":"Heavy rain upstream has swollen the crossing.",
		"choices":[
			{"text":"Float the wagon across","chance":0.55,
				"on_success":{"res":{"food":-3},"log":"It floats true. You make the far bank."},
				"on_fail":{"res":{"food":-10,"clothing":-3,"parts":-2},"log":"The current nearly takes it all."}},
			{"text":"Wait it out","effects":{"res":{"food":-5,"feed":-3},"morale":-2,"log":"You camp and wait for the water to fall."}},
		]},
	{"id":"horse_trade","title":"Fresh Animals","weight":1,
		"text":"A rancher offers to swap your tired team for fresh stock.",
		"choices":[
			{"text":"Trade (10 coin)","effects":{"res":{"money":-10,"feed":4},"morale":3,"log":"Fresh legs under the wagon."}},
			{"text":"Decline","effects":{"log":"Your team has more in them yet."}},
		]},
	{"id":"funeral","title":"A Roadside Grave","weight":1,
		"text":"You pass a fresh grave marked only with a coat.",
		"choices":[
			{"text":"Pay your respects","effects":{"morale":-1,"bond":{"who":"all","amount":3},
				"log":"A quiet moment binds the party closer."}},
			{"text":"Hurry past","effects":{"morale":-2,"log":"No time for the dead."}},
		]},
	{"id":"fog_bank","title":"Into the Fog","weight":2,
		"text":"A thick fog swallows the trail.",
		"choices":[
			{"text":"Wait for it to lift","effects":{"res":{"food":-3,"feed":-2},"log":"You lose half a day to grey nothing."}},
			{"text":"Feel your way forward","chance":0.6,
				"on_success":{"log":"You keep the line and press on."},
				"on_fail":{"res":{"parts":-2},"morale":-2,"log":"You drift off-trail and clip a boulder."}},
		]},
	{"id":"stowaway","title":"A Hungry Child","weight":1,
		"text":"A child has been following the wagon, half-starved.",
		"choices":[
			{"text":"Feed and shelter them","effects":{"res":{"food":-6},"morale":8,"bond":{"who":"all","amount":6},
				"log":"The party rallies around the child. Spirits soar."}},
			{"text":"You can't spare it","effects":{"morale":-6,"log":"You drive on. No one speaks for miles."}},
		]},
	# --- production expansion set (recruits, hazards, towns) ---
	{"id":"orphan_recruit","title":"A Child Alone","weight":1,
		"text":"A half-grown orphan begs to come along, swearing to earn their keep.",
		"choices":[
			{"text":"Take them in","effects":{"recruit":true,"morale":4,"res":{"food":-4},"log":"A new face at the fire."}},
			{"text":"Leave them at the next town","effects":{"morale":-3,"log":"You find them a roof, and move on."}},
		]},
	{"id":"veteran_recruit","title":"The Old Soldier","weight":1,
		"text":"A grizzled veteran offers his rifle and his road-sense for a share of the food.",
		"choices":[
			{"text":"Sign him on","effects":{"recruit":true,"res":{"ammo":3},"log":"He tosses you a handful of cartridges as he climbs aboard."}},
			{"text":"Decline","effects":{"log":"He shrugs and walks on."}},
		]},
	{"id":"healer_recruit","title":"A Wandering Healer","weight":1,
		"text":"A herbalist with a heavy satchel asks to travel under your protection.",
		"choices":[
			{"text":"Welcome them","effects":{"recruit":true,"res":{"medicine":3},"log":"Their satchel is worth its weight in safety."}},
			{"text":"Too many mouths","effects":{"morale":-2,"log":"You wave them off."}},
		]},
	{"id":"boatman_recruit","title":"The Ferryman's Son","weight":1,
		"text":"A young boatman, out of work since the ferry sank, wants passage and purpose.",
		"choices":[
			{"text":"Bring him along","effects":{"recruit":true,"log":"He grins. 'You'll be glad come the next river.'"}},
			{"text":"Send him home","effects":{"log":"He watches you go from the bank."}},
		]},
	{"id":"prairie_fire","title":"Wall of Fire","weight":2,
		"text":"Grassfire races across the plain toward the wagon.",
		"choices":[
			{"text":"Backfire a gap and shelter","chance":0.7,
				"on_success":{"res":{"feed":-3},"log":"You burn a safe patch and let it pass."},
				"on_fail":{"res":{"feed":-6,"clothing":-2},"health":{"amount":-12,"target":"all"},"log":"The fire jumps your line. Singed and shaken."}},
			{"text":"Outrun it","effects":{"res":{"feed":-5},"health":{"amount":-6,"target":"random"},"morale":-2,"log":"A frantic gallop through smoke."}},
		]},
	{"id":"dust_storm","title":"The Brown Wind","weight":2,
		"text":"A wall of dust blots out the sun.",
		"choices":[
			{"text":"Hunker down","effects":{"res":{"water":-4,"food":-2},"log":"You wait, chewing grit, until it clears."}},
			{"text":"Press blind","effects":{"inflict":{"who":"random","cond":"campsick"},"morale":-2,"log":"Choking dust gets into lungs and eyes."}},
		]},
	{"id":"quicksand","title":"Sucking Ground","weight":2,
		"text":"A wheel sinks into hidden bog.",
		"choices":[
			{"text":"Unload and lever it out","effects":{"res":{"food":-3},"health":{"amount":-5,"target":"all"},"log":"Backbreaking, but you save the wagon."}},
			{"text":"Drive hard to break free","chance":0.5,
				"on_success":{"log":"The team heaves and you lurch onto firm ground."},
				"on_fail":{"res":{"parts":-3,"feed":-3},"log":"You free it, but the axle is wrenched."}},
		]},
	{"id":"alligator","title":"Eyes in the Water","weight":1,
		"text":"Something large slides off the bank as you ford the swamp.",
		"choices":[
			{"text":"Fire to scare it","effects":{"res":{"ammo":-2},"log":"A shot, a thrash, and it's gone."}},
			{"text":"Cross fast and quiet","chance":0.6,
				"on_success":{"log":"You slip across untouched."},
				"on_fail":{"health":{"amount":-16,"target":"random"},"inflict":{"who":"random","cond":"injury"},"log":"It takes a bite before you drive it off."}},
		]},
	{"id":"swamp_fever","title":"Marsh Sickness","weight":2,
		"text":"The bad air of the mire settles into someone's chest.",
		"choices":[
			{"text":"Dose and rest","effects":{"res":{"medicine":-2,"food":-2},"cure":{"who":"worst","cond":"campsick"},"log":"You catch it early."}},
			{"text":"Push for higher ground","effects":{"inflict":{"who":"random","cond":"campsick"},"morale":-2,"log":"You climb out of the wet, but late."}},
		]},
	{"id":"bridge_out","title":"The Broken Bridge","weight":2,
		"text":"The only bridge has collapsed into the gorge.",
		"choices":[
			{"text":"Rebuild a span (parts)","effects":{"res":{"parts":-3,"food":-2},"log":"A day's carpentry and you cross."}},
			{"text":"Ford downstream","chance":0.55,
				"on_success":{"res":{"food":-2},"log":"A rough ford, but you make it."},
				"on_fail":{"res":{"food":-8,"clothing":-2},"log":"The crossing costs you dearly in soaked stores."}},
		]},
	{"id":"trappers","title":"Friendly Trappers","weight":2,
		"text":"A trapper camp waves you in for the night.",
		"choices":[
			{"text":"Trade pelts for food","effects":{"res":{"money":-4,"food":10},"morale":3,"log":"A warm camp and full bellies."}},
			{"text":"Swap stories only","effects":{"morale":4,"bond":{"who":"all","amount":3},"log":"Tales by the fire lift the party."}},
		]},
	{"id":"gold_rumor","title":"Rumor of Gold","weight":1,
		"text":"A drifter swears there's gold in the hills just off-trail.",
		"choices":[
			{"text":"Detour to dig","chance":0.3,
				"on_success":{"res":{"money":20},"morale":4,"log":"By some miracle, the rumor was true."},
				"on_fail":{"res":{"food":-8,"feed":-4,"water":-4},"morale":-4,"log":"Days wasted chasing a lie."}},
			{"text":"Ignore it","effects":{"log":"You've a road to keep."}},
		]},
	{"id":"claim_jumpers","title":"Claim Jumpers","weight":1,
		"text":"Armed men accuse you of crossing their land.",
		"choices":[
			{"text":"Pay them off (6 coin)","effects":{"res":{"money":-6},"log":"Cheaper than blood."}},
			{"text":"Stand your ground","chance":0.5,
				"on_success":{"log":"They blink first and let you pass."},
				"on_fail":{"res":{"money":-8,"food":-6},"health":{"amount":-8,"target":"random"},"log":"It comes to blows. You lose more than coin."}},
		]},
	{"id":"quarantine","title":"A Closed Town","weight":1,
		"text":"The town ahead is under quarantine — sickness within.",
		"choices":[
			{"text":"Skirt around it","effects":{"res":{"food":-5,"feed":-3},"log":"The long way keeps you clean."}},
			{"text":"Slip in for supplies","chance":0.5,
				"on_success":{"res":{"food":8,"medicine":2},"log":"You trade quick and get out."},
				"on_fail":{"inflict":{"who":"random","cond":"campsick"},"res":{"food":6},"log":"You got the goods — and the sickness."}},
		]},
	{"id":"town_doctor","title":"A Town Doctor","weight":2,
		"text":"A proper doctor keeps an office in the next settlement.",
		"choices":[
			{"text":"Treat the worst-off (10 coin)","effects":{"res":{"money":-10},"health":{"amount":25,"target":"worst"},
				"cure":{"who":"worst","cond":"fever"},"log":"Real care. They look human again."}},
			{"text":"Just buy medicine (8 coin)","effects":{"res":{"money":-8,"medicine":3},"log":"You stock the kit instead."}},
		]},
	{"id":"blacksmith","title":"The Blacksmith","weight":2,
		"text":"A smith offers to reinforce the wagon's iron.",
		"choices":[
			{"text":"Pay for repairs (8 coin)","effects":{"res":{"money":-8,"parts":3},"log":"The wagon's never rolled truer."}},
			{"text":"Trade labor for parts","effects":{"res":{"food":-3,"parts":2},"log":"A day's sweat earns you spare iron."}},
		]},
	{"id":"runaway_oxen","title":"Spooked Team","weight":2,
		"text":"A snake spooks the oxen and they bolt.",
		"choices":[
			{"text":"Chase them down","chance":0.7,
				"on_success":{"res":{"food":-2},"log":"You catch them, winded but whole."},
				"on_fail":{"res":{"feed":-4,"parts":-2},"morale":-3,"log":"They drag the wagon into a ditch first."}},
			{"text":"Let them tire out","effects":{"res":{"food":-3,"feed":-3},"log":"You wait, then gather them up."}},
		]},
	{"id":"wagon_fire","title":"Fire in the Wagon","weight":1,
		"text":"A lantern tips in the night and the canvas catches.",
		"choices":[
			{"text":"Beat it out fast","chance":0.7,
				"on_success":{"res":{"clothing":-1},"log":"Scorched canvas, nothing worse."},
				"on_fail":{"res":{"food":-8,"clothing":-3,"medicine":-1},"morale":-3,"log":"You save the wagon but lose stores to flame."}},
			{"text":"Douse with the water casks","effects":{"res":{"water":-8},"log":"You drown the fire — and your drinking water."}},
		]},
	{"id":"hail","title":"Hammering Hail","weight":2,
		"text":"Hailstones the size of fists pound down.",
		"choices":[
			{"text":"Shelter under the wagon","effects":{"res":{"food":-2},"log":"Battered tin and bruised pride, but safe."}},
			{"text":"Keep rolling","effects":{"health":{"amount":-8,"target":"all"},"res":{"clothing":-2},"morale":-2,"log":"Everyone takes a beating."}},
		]},
	{"id":"drought_stretch","title":"The Long Dry","weight":2,
		"text":"No water for two days of trail, by the map.",
		"choices":[
			{"text":"Ration hard","effects":{"res":{"water":-6},"morale":-3,"log":"Cracked lips and short tempers."}},
			{"text":"Detour to a rumored spring","chance":0.6,
				"on_success":{"res":{"water":12},"log":"The spring is real and sweet."},
				"on_fail":{"res":{"water":-8,"feed":-3},"morale":-3,"log":"The spring is dry. A costly gamble."}},
		]},
	{"id":"flash_flood","title":"Flash Flood","weight":1,
		"text":"A dry wash fills with a wall of water in minutes.",
		"choices":[
			{"text":"Race to high ground","chance":0.7,
				"on_success":{"log":"You crest the bank as the flood roars past."},
				"on_fail":{"res":{"food":-10,"feed":-4,"parts":-2},"log":"The water catches the wagon's tail."}},
			{"text":"Cut the team loose to save them","effects":{"res":{"feed":-3,"parts":-3},"morale":-2,"log":"You save the animals; the wagon suffers."}},
		]},
	{"id":"ambush","title":"Ambush in the Rocks","weight":1,
		"text":"Bandits rise from cover, rifles leveled.",
		"choices":[
			{"text":"Fight (ammo)","chance":0.55,
				"on_success":{"res":{"ammo":-3},"log":"A short, sharp fight. They break and run."},
				"on_fail":{"res":{"ammo":-3,"money":-8,"food":-6},"health":{"amount":-12,"target":"random"},"log":"You drive them off, but pay in blood and stores."}},
			{"text":"Surrender supplies","effects":{"res":{"money":-10,"food":-8},"morale":-4,"log":"You hand over what they want and live."}},
		]},
	{"id":"deserter_returns","title":"A Familiar Shadow","weight":1,
		"text":"Someone who left the party weeks ago catches up, contrite.",
		"choices":[
			{"text":"Take them back","effects":{"recruit":true,"morale":3,"bond":{"who":"all","amount":-2},"log":"Forgiveness, grudgingly given."}},
			{"text":"Turn them away","effects":{"morale":-2,"log":"Some doors don't reopen."}},
		]},
	{"id":"hidden_cache","title":"A Buried Cache","weight":1,
		"text":"Boone spots disturbed earth and the corner of a crate.",
		"choices":[
			{"text":"Dig it up","effects":{"res":{"food":8,"ammo":2,"parts":1},"morale":2,"log":"Someone's hidden stores, now yours."}},
		]},
	{"id":"map_seller","title":"The Map Seller","weight":1,
		"text":"A peddler hawks 'the only true map of the road ahead.'",
		"choices":[
			{"text":"Buy it (5 coin)","chance":0.6,
				"on_success":{"res":{"money":-5,"food":4},"morale":2,"log":"The map is good — it shows a shortcut and a spring."},
				"on_fail":{"res":{"money":-5},"morale":-2,"log":"The map is nonsense. You've been had."}},
			{"text":"Decline","effects":{"log":"You trust your own eyes."}},
		]},
	{"id":"preacher_recruit","title":"The Roadside Preacher","weight":1,
		"text":"A preacher walking to the valley asks to share the road.",
		"choices":[
			{"text":"Let him join","effects":{"recruit":true,"morale":6,"bond":{"who":"all","amount":4},"log":"His calm spreads through the camp."}},
			{"text":"Politely decline","effects":{"log":"He blesses you and walks on."}},
		]},
	{"id":"card_game","title":"A Game of Cards","weight":1,
		"text":"At a waystation, a sharp-eyed gambler deals you in.",
		"choices":[
			{"text":"Play for coin","chance":0.5,
				"on_success":{"res":{"money":12},"morale":3,"log":"Lady luck rides with you tonight."},
				"on_fail":{"res":{"money":-12},"morale":-3,"log":"You should have folded."}},
			{"text":"Just watch","effects":{"morale":1,"log":"Wiser to keep your coin."}},
		]},
	{"id":"drunk_night","title":"A Bottle Too Many","weight":1,
		"text":"The party finds a cache of liquor in an abandoned cabin.",
		"choices":[
			{"text":"Let them celebrate","effects":{"morale":8,"bond":{"who":"all","amount":4},"res":{"food":-2},"inflict":{"who":"random","cond":"exhaustion"},"log":"A loud night, a slow morning."}},
			{"text":"Pour it out","effects":{"morale":-4,"log":"Sober and resentful, but moving."}},
		]},
	{"id":"lost_rifle","title":"A Rifle in the Reeds","weight":1,
		"text":"A serviceable rifle and a box of cartridges, half-sunk in mud.",
		"choices":[
			{"text":"Clean it up","effects":{"res":{"ammo":4},"morale":2,"log":"Good iron, free of charge."}},
		]},
	{"id":"bear","title":"Bear at the Camp","weight":1,
		"text":"A bear, drawn by the food stores, lumbers into camp.",
		"choices":[
			{"text":"Drive it off (ammo)","chance":0.7,
				"on_success":{"res":{"ammo":-2},"log":"A volley sends it crashing into the trees."},
				"on_fail":{"res":{"ammo":-2,"food":-10},"health":{"amount":-14,"target":"random"},"inflict":{"who":"random","cond":"injury"},"log":"It mauls a member and raids the larder."}},
			{"text":"Sacrifice some food","effects":{"res":{"food":-8},"morale":-1,"log":"You buy your safety with bread."}},
		]},
	{"id":"hot_spring","title":"A Warm Spring","weight":1,
		"text":"Steam rises from a hidden hot spring.",
		"choices":[
			{"text":"Rest and soak","effects":{"res":{"food":-2},"morale":8,"health":{"amount":8,"target":"all"},"bond":{"who":"all","amount":4},"log":"Warmth in the bones. The party is reborn."}},
			{"text":"No time to linger","effects":{"morale":-1,"log":"You press on, longingly."}},
		]},
	{"id":"fishing","title":"A Good Fishing Hole","weight":2,
		"text":"A still pool teems with fish.",
		"choices":[
			{"text":"Stop and fish","effects":{"res":{"food":10},"morale":3,"log":"A fine catch, smoked for the road."}},
			{"text":"Keep moving","effects":{"log":"You note it on the map and roll on."}},
		]},
	{"id":"cave_shelter","title":"A Dry Cave","weight":1,
		"text":"A cave offers shelter from a coming storm.",
		"choices":[
			{"text":"Camp inside","effects":{"morale":3,"res":{"feed":-1},"log":"Snug and dry while the storm rages."}},
			{"text":"Push past it","effects":{"res":{"clothing":-2},"health":{"amount":-6,"target":"all"},"log":"You take the storm head-on instead."}},
		]},
	{"id":"abandoned_fort","title":"The Empty Fort","weight":1,
		"text":"A derelict frontier fort, long abandoned.",
		"choices":[
			{"text":"Search it","effects":{"res":{"parts":2,"ammo":2,"clothing":2},"morale":-1,"log":"Useful salvage among the ruins."}},
			{"text":"Camp safely behind its walls","effects":{"morale":4,"log":"Stone walls make for an easy night."}},
		]},
	{"id":"valley_folk","title":"The Valley Folk","weight":2,
		"text":"People native to this country approach, curious and wary.",
		"choices":[
			{"text":"Offer a respectful trade","effects":{"res":{"money":-4,"food":10,"medicine":1},"morale":4,"bond":{"who":"all","amount":3},"log":"A fair exchange. They point you to clean water."}},
			{"text":"Keep your distance","effects":{"morale":-1,"log":"You pass without contact, the poorer for it."}},
		]},
	{"id":"sacred_ground","title":"Marked Ground","weight":1,
		"text":"The trail crosses ground clearly held sacred by the valley folk.",
		"choices":[
			{"text":"Detour respectfully","effects":{"res":{"food":-4,"feed":-2},"morale":3,"log":"The long way, with a clear conscience."}},
			{"text":"Cross it anyway","effects":{"morale":-5,"bond":{"who":"all","amount":-4},"log":"You make time, and lose something harder to name."}},
		]},
	{"id":"festival","title":"A Settlement Festival","weight":1,
		"text":"A frontier town is mid-celebration as you arrive.",
		"choices":[
			{"text":"Join the dancing","effects":{"res":{"money":-3,"food":6},"morale":10,"bond":{"who":"all","amount":6},"log":"A night of music. The party glows."}},
			{"text":"Trade and move on","effects":{"res":{"money":-4,"food":8},"log":"Business before pleasure."}},
		]},
	{"id":"newborn","title":"A Birth on the Trail","weight":1,
		"text":"Against all odds, new life arrives in the night.",
		"choices":[
			{"text":"Rest a day for mother and child","effects":{"res":{"food":-4,"water":-3},"morale":12,"bond":{"who":"all","amount":8},"log":"Joy, fierce and unexpected, binds the party."}},
			{"text":"Move carefully on","effects":{"morale":4,"log":"You press on, gentle with the load."}},
		]},
	{"id":"ghost_story","title":"Tales in the Dark","weight":1,
		"text":"Around the fire, the talk turns to ghosts of the trail.",
		"choices":[
			{"text":"Spin a good yarn","effects":{"morale":5,"bond":{"who":"all","amount":3},"log":"Laughter and shivers, both welcome."}},
			{"text":"Tell them to sleep","effects":{"morale":-1,"log":"You snuff the fire and the fun."}},
		]},
	{"id":"meteor","title":"A Sky of Falling Stars","weight":1,
		"text":"The night sky streaks with falling stars.",
		"choices":[
			{"text":"Wake everyone to watch","effects":{"morale":7,"bond":{"who":"all","amount":4},"log":"A wonder shared. Spirits soar."}},
			{"text":"Let them sleep","effects":{"morale":1,"log":"You watch alone, and let them rest."}},
		]},
	{"id":"first_snow","title":"First Snow","weight":2,
		"text":"The season's first snow dusts the trail.",
		"choices":[
			{"text":"Break out winter gear early","effects":{"res":{"clothing":-2},"morale":2,"log":"Ahead of the cold, for once."}},
			{"text":"Tough it out a while longer","effects":{"inflict":{"who":"random","cond":"frostbite"},"log":"You wait too long; the cold bites."}},
		]},
	{"id":"mushrooms","title":"Forest Mushrooms","weight":1,
		"text":"Mushrooms carpet a damp glade.",
		"choices":[
			{"text":"Gather the ones you know","effects":{"res":{"food":6},"log":"A safe, modest harvest."}},
			{"text":"Take all of them","chance":0.55,
				"on_success":{"res":{"food":12},"morale":2,"log":"A feast, and no ill effects."},
				"on_fail":{"inflict":{"who":"all","cond":"campsick"},"res":{"food":6},"log":"Some were the wrong kind. A miserable night."}},
		]},
	{"id":"tax_collector","title":"The Tax Man","weight":1,
		"text":"A territorial official demands a 'transit fee.'",
		"choices":[
			{"text":"Pay it (7 coin)","effects":{"res":{"money":-7},"log":"Stamped, sealed, and on your way."}},
			{"text":"Argue the charge","chance":0.5,
				"on_success":{"res":{"money":-2},"morale":2,"log":"You haggle him down to almost nothing."},
				"on_fail":{"res":{"money":-10},"morale":-2,"log":"He adds a fine for your trouble."}},
		]},
	{"id":"refugees","title":"Refugees on the Road","weight":1,
		"text":"A column of refugees shares grim news of the way ahead.",
		"choices":[
			{"text":"Share what food you can","effects":{"res":{"food":-8},"morale":6,"bond":{"who":"all","amount":4},"log":"Hard to give, harder not to. The party stands taller."}},
			{"text":"Trade for their news only","effects":{"morale":-1,"log":"You learn the road ahead, and keep your stores."}},
		]},
	{"id":"tide_crossing","title":"The Tidal Flats","weight":2,
		"text":"The coast road crosses flats passable only at low tide.",
		"choices":[
			{"text":"Wait for the tide","effects":{"res":{"food":-4,"feed":-2},"log":"You time it right and cross dry."}},
			{"text":"Risk the rising water","chance":0.5,
				"on_success":{"log":"You beat the tide by a length."},
				"on_fail":{"res":{"food":-8,"clothing":-3,"feed":-3},"health":{"amount":-8,"target":"all"},"log":"The sea catches you mid-flat."}},
		]},
	{"id":"shipwreck","title":"Wreck on the Shore","weight":1,
		"text":"A wrecked coastal trader lies broken on the rocks.",
		"choices":[
			{"text":"Salvage the hold","effects":{"res":{"food":8,"clothing":3,"parts":2},"morale":-1,"log":"The sea's loss, your gain."}},
			{"text":"Leave it to the gulls","effects":{"morale":1,"log":"You leave the dead their cargo."}},
		]},
]

# --- endings (relationship-aware) ---
func get_ending(survivors: int, avg_morale: float) -> Dictionary:
	if survivors <= 0:
		return {"id":"fail","title":"The Reach Claims All",
			"text":"The wagon rolls to a stop with no one left to drive it. The frontier keeps its toll. Somewhere ahead, the green valleys go unseen.",
			"good":false}
	if survivors >= 4 and avg_morale >= 55:
		return {"id":"triumph","title":"Into the Green Valleys",
			"text":"You crest the final pass together and the valley opens below — rivers, timber, room to breathe. You arrived whole, and you arrived as one.",
			"good":true}
	return {"id":"bittersweet","title":"What the Road Took",
		"text":"You reach the valley thinner, quieter, fewer. You made it — but the country exacted its price, and you'll carry the empty seats at the fire for a long time.",
		"good":true}
